arch = [
	"acpi",
	"acpi_call-dkms",
	"acpid",
	"alsa-firmware",
	"alsa-oss",
	"alsa-utils",
	"ananicy-cpp",
	"android-udev",
	"apparmor",
	"arch-audit",
	"arch-install-scripts",
	"archiso-systemd-boot",
	"atool",
	"base",
	"base-devel",
	"bind",
	"bluez-utils",
	"btrfs-progs",
	"cachyos-ananicy-rules-git",
	"ccache",
	"compsize",
	"cups",
	"cups-pdf",
	"devtools",
	"dhclient",
	"dhcp",
	"dialog",
	"djvulibre",
	"dmidecode",
	"dnsmasq",
	"docker",
	"dosfstools",
	"doxygen",
	"efibootmgr",
	"electron",
	"ethtool",
	"evemu",
	"evtest",
	"exfat-utils",
	"expac",
	"f2fs-tools",
	"fakeroot",
	"ffmpegthumbnailer",
	"file",
	"findutils",
	"fish",
	"fisher",
	"flatpak",
	"flex",
	"fwupd",
	"fzf",
	"gettext",
	"grep",
	"grml-zsh-config",
	"groff",
	"help2man",
	"hplip",
	"hunspell",
	"hunspell-de",
	"hunspell-en_us",
	"icoutils",
	"keychain",
	"libfbclient",
	"libgee",
	"libgit2",
	"libgsf",
	"libmicrohttpd",
	"libopenraw",
	"linux-firmware",
	"linux-lts",
	"linux-lts-headers",
	"linux-zen",
	"linux-zen-headers",
	"logrotate",
	"man-db",
	"man-pages",
	"mbuffer",
	"metapac",
	"mokutil",
	"muparser",
	"net-tools",
	"netcdf",
	"netctl",
	"networkmanager-openvpn",
	"nss-mdns",
	"ntfs-3g",
	"ntp",
	"nushell",
	"nvimpager",
	"ocl-icd",
	"odt2txt",
	"opendoas",
	"openvpn",
	"pacgraph",
	"pacman",
	"pacman-contrib",
	"perl-file-mimeinfo",
	"perl-image-exiftool",
	"pipewire",
	"pipewire-alsa",
	"pipewire-pulse",
	"pipewire-v4l2",
	"pistol-bin",
	"pkgconf",
	"pkgfile",
	"pkgstats",
	"plymouth",
	"plymouth-theme-arch-logo",
	"pv",
	"python",
	"python-distutils-extra",
	"rebuild-detector",
	"samba",
	"sane",
	"sbsigntools",
	"schroedinger",
	"screen",
	"sg3_utils",
	"shim-signed",
	"smbclient",
	"sparsehash",
	"sshfs",
	"strace",
	"sudo",
	"udftools",
	"usb_modeswitch",
	"usbutils",
	"wireplumber",
	"x86_energy_perf_policy",
	"xdg-user-dirs",
	"xdg-utils-handlr",
	"yay-bin",
	"zsh",
	"zsh-completions",
]

