[general]
live_config_reload = true
import = [
	"~/.config/alacritty/keybindings.toml",
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = -1
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
program = "/usr/bin/fish"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.75
blur = true

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[terminal]

